version: "3"
services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: NODE_OPTIONS=-max_old_space_size=8192 ganache-cli -h 0.0.0.0 --gasLimit=0x1C9C380 --callGasLimit=0x1C9C380 -m "${GANACHE_MNEMONIC}"
    volumes:
      - ./data/ganache:/data/ganache