version: "3"
services:
  ganache:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"
    command: --wallet.mnemonic="${GANACHE_MNEMONIC}"
    volumes:
      - ./data/ganache:/data/ganache
    networks:
      - nft_auction

networks:
  nft_auction:
    name: nft_auction
